name: Build and Test

on:
  push:
    branches:
      - main  # Run workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Run workflow on pull requests to the 'main' branch
  workflow_dispatch:  # Allows manually triggering the workflow

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Set Java version to 17
          distribution: 'temurin'  # Use the Temurin distribution for JDK 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        run: mvn clean install -DtrimStackTrace=false -Dsurefire.printSummary=true
