name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Run workflow on pull requests to the 'main' branch
  workflow_dispatch:  # Allows manually triggering the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Set Java version to 17
          distribution: 'temurin'  # Use the Temurin distribution for JDK 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Only run Docker steps on the 'main' branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Updated to latest version compatible with Node.js 20

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3  # Updated to latest version compatible with Node.js 20
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/web-scraper:latest .
          docker push ghcr.io/${{ github.repository_owner }}/web-scraper:latest
